### ISSUE TITLE
Battery Control not working on my Huawei Matebook D AMD 2018 edition

### ISSUE THREAD

**Issue by Rolo1973** [qu1x/huawei-wmi#16] opened 2022-08-21 19:12 UTC
Hi,

on my Huawei matebook D AMD (Arch KDE) Huawei WMI does not work for battery protection. I have a problem with all the distro I tried those years (Ubuntu, Arch, Manjaro, Debian based and so on) that on ma laptop that is a Huawei Matebook D AMD SoC even if Huawei-WMI driver is included in the kernel (so I can use FN key and OSD for volume ...) the battery protection doesn't work even in theory system say it stop charging at 70% , it charge 100%.
if I boot to windows (with HuaweiPCManager that set battery to 70%) and reboot to linux battery stay at 70% but after 2 or 3 reboot to linux it loose the setting and goes to fully charged 100%, because of that I install Huawei-WMI to sets group write privileges and reinstates battery charge-thresholds. I have 2 services : huawei-wmi-reinstate and huawei-wmi-privilege but both are unloaded and inactive on systemd, how to get those 2 service loaded at startup and active? Trying to activate I have this error: $ sudo systemctl enable --now huawei-wmi-privilege.service Unit /usr/lib/systemd/system/huawei-wmi-privilege.service is added as a depende ncy to a non-existent unit sys-devices-platform-huawei\x2dwmi.device
Command sudo systemctl enable --now huawei-wmi-reinstate.service doesn,t provide errors but is not active and still unloaded
Can you check? Battery protection is the only thing not working on my huawei Matebook D 2018 version AMD
Thanks!!!

**Comment by ahmetlii** [comment] 2023-02-17 23:25
Having the same issue.

**Comment by n3vu0r** [comment] 2023-02-19 09:41
Hi, sorry for replying so late.

I will first summarize how the services work:

Both services `huawei-wmi-privilege` and `huawei-wmi-reinstate` are of `Type=oneshot`. That means they don't run in the background. Instead, they are fired on certain events and execute a shell script. After that, they are inactive again until a new event gets fired. So they only need to be enabled with:

```
systemctl enable huawei-wmi-privilege huawei-wmi-reinstate
```

  * `huawei-wmi-privilege`: When booting the Matebook, the kernel driver will create the folder `/sys/devices/platform/huawei-wmi` and some files inside it to control the Huawei WMI firmware. This repository provides following udev rule as part of the file `10-huawei-wmi.rules`:

    ```
    SUBSYSTEM=="platform", DRIVER=="huawei-wmi", ACTION=="add", TAG+="systemd"
    ```

    This rule is triggered when the kernel driver created the mentioned folder and it will delegate this event to systemd which fires the service `huawei-wmi-privilege`. It will run a shell script to set file permissions. It will give write access to the users you have configured when installing this repository via Makefile or Debian/Arch package. After this, it will fire the `huawei-wmi-reinstate` service. This happens on every boot as soon as the kernel driver has recreated the mentioned folder.

  * `huawei-wmi-reinstate`: This service will copy the settings from `/etc/default/huawei-wmi` to the previously mention folder created by the kernel driver. The settings in `/etc/default/huawei-wmi` are either manually configured by you or by using the `matebook-applet`. This service is additionally fired after all different sleep/suspend/hibernation modes. This service is necessary because the Huawei WMI controller/firmware does not persistently remember these settings by its own.

You did already a good test with

>Trying to activate I have this error: $ sudo systemctl enable --now huawei-wmi-privilege.service Unit /usr/lib/systemd/system/huawei-wmi-privilege.service is added as a depende ncy to a non-existent unit sys-devices-platform-huawei\x2dwmi.device

where

> non-existent unit sys-devices-platform-huawei\x2dwmi.device

seems to mean that the kernel driver has not created the folder `/sys/devices/platform/huawei-wmi` and hence is not successfully loaded. Usually, new kernels versions contain this driver and manually loading this module is not required. Can you please check that the folder exists with some files inside:

```sh
ls -l /sys/devices/platform/huawei-wmi
```

**Comment by ahmetlii** [comment] 2023-02-19 19:44
Hello, and thanks for the reply. I've executed the provided command, the files exist and couldn't spot a meaningful issue either:
```
$ ls -l /sys/devices/platform/huawei-wmi
total 0
-rw-rw-r-- 1 root huawei-wmi 4096 Feb 19 22:16 charge_control_thresholds
lrwxrwxrwx 1 root root          0 Feb 19 19:05 driver -> ../../../bus/platform/drivers/huawei-wmi
-rw-r--r-- 1 root root       4096 Feb 19 22:25 driver_override
-rw-rw-r-- 1 root huawei-wmi 4096 Feb 19 22:16 fn_lock_state
drwxr-xr-x 3 root root          0 Feb 19 19:05 input
drwxr-xr-x 3 root root          0 Feb 19 19:05 leds
-r--r--r-- 1 root root       4096 Feb 19 22:25 modalias
drwxr-xr-x 2 root root          0 Feb 19 19:21 power
lrwxrwxrwx 1 root root          0 Feb 19 19:05 subsystem -> ../../../bus/platform
-rw-r--r-- 1 root root       4096 Feb 19 19:05 uevent
```
However, after issuing `systemctl status huawei-wmi-reinstate` command I've spotted:
```
systemd[1]: [🡕] /usr/lib/systemd/system/huawei-wmi-reinstate.service:8: Special user nobody configured, this is not safe!
```
so I suspect there's something wrong going on with setting user rights.

**Comment by n3vu0r** [comment] 2023-02-19 20:24
Thanks, so the kernel module works. The warning was already reported in #12 and there is a commit but a release is still missing. For now you can manually replace `User=nobody` with `DynamicUser=yes` in `/usr/lib/systemd/system/huawei-wmi-reinstate.service` and run `systemctl daemon-reload`. But I think it will not fix this issue.

I see that `/sys/devices/platform/huawei-wmi/charge_control_thresholds` has the correct user goup `huawei-wmi`. That means, `huawei-wmi-privilege.service` did its job. Since you haven't seen other errors with `systemctl status huawei-wmi-reinstate`, the only thing left is to manually check that the configured values match the reinstated values:

```sh
cat /etc/default/huawei-wmi/charge_control_thresholds
cat /sys/devices/platform/huawei-wmi/charge_control_thresholds
```

Both should show the same thresholds. You might want to check this two or three times after reboot or after hibernation.

Just to clarify a surprising but expected behavior:

When you shutdown the Matebook, the charge thresholds will be respected as long as the power supply is connected. But when the Matebook is shutdown and you unplug and re-plug the power supply or there is a short power outage, the controller/firmware gets reset and there is nothing which can reinstate the charge thresholds and it will charge to 100 %. This should be the same with Windows and Linux.

**Comment by ahmetlii** [comment] 2023-02-20 15:28
the values are not same when I change the default settings, and `cat` says "access denied" for accessing to `/etc/default/huawei-wmi/charge_control_thresholds`. I've also pulled and ``make install``'d newest commits on ``/generic`` branch, still no luck.
``sudo ls -l`` for ``/etc/default/huawei-wmi/charge_control_thresholds`` outputs:
``-rw-rw-r-- 1 root huawei-wmi 6 Feb 20 17:39 /etc/default/huawei-wmi/charge_control_thresholds``
Changed perms for others to read and write, still not working. I've also checked ``sudo ls -l /etc/default/``:
```
drwxr-sr-x+ 1 root huawei-wmi  50 Feb 20 17:39 huawei-wmi
-rw-------  1 root root       667 Jan 25 11:29 useradd
```
as well as ``ls -l /etc/``
``drwxr-xr-x 1 root root     34 Feb 17 23:06 default``

**Comment by n3vu0r** [comment] 2023-02-20 15:55
>  `cat` says "access denied" for accessing to /etc/default/huawei-wmi/charge_control_thresholds

When you installed with `make install`, I assume you have entered your desktop username? The `Makefile` will add your username to the group `huawei-wmi`. You can confirm this with the command `id your-username`, it should list the group `huawei-wmi` among others (maybe you need to logout first, or reboot).

> -rw-rw-r-- 1 root huawei-wmi 6 Feb 20 17:39 /etc/default/huawei-wmi/charge_control_thresholds

This is correct, only the users in the group `huawei-wmi` should have write access.

> drwxr-sr-x+ 1 root huawei-wmi  50 Feb 20 17:39 huawei-wmi

This is also correct, the `s` means, that new files will automatically be writable by group members.

Do you use the `matebook-applet`? I assume the applet hasn't have write access to the default values. This is the case when your desktop username is not a member of the group `huawei-wmi`. Usually, the `matebook-applet` is run by the desktop user.

**Comment by ahmetlii** [comment] 2023-02-20 16:33
> When you installed with `make install`, I assume you have entered your desktop username? The `Makefile` will add your username to the group `huawei-wmi`. You can confirm this with the command `id your-username`, it should list the group `huawei-wmi` among others (maybe you need to logout first, or reboot).

Yes. I've followed all of the steps, also reassigned groups etc. and still broken.

> Do you use the `matebook-applet`? I assume the applet hasn't have write access to the default values. This is the case when your desktop username is not a member of the group `huawei-wmi`. Usually, the `matebook-applet` is run by the desktop user.

Yes, I use it. Weird that it doesn't have write access, nor my desktop user.

**Comment by n3vu0r** [comment] 2023-02-21 07:38
When you run the `id` command **without** `sudo`, does its output contain `huawei-wmi`?

**Comment by ahmetlii** [comment] 2023-02-21 18:47
> When you run the `id` command **without** `sudo`, does its output contain `huawei-wmi`?

Yes.

**Comment by n3vu0r** [comment] 2023-02-21 23:18
Ok, then I would say, this repository is correctly set up. How do you launch the matebook-applet? Can you instead launch it manually from the terminal to ensure it is actually running as the desktop user?

**Comment by ahmetlii** [comment] 2023-02-22 14:17
> Ok, then I would say, this repository is correctly set up. How do you launch the matebook-applet? Can you instead launch it manually from the terminal to ensure it is actually running as the desktop user?

I am using KDE's autostart. I've ran it from the command line and still not working either.

**Comment by n3vu0r** [comment] 2023-02-22 14:42
Hm, I'm currently out of ideas. I have the same Matebook (Model: KPL-W00). I'm running Arch Linux with Gnome and used the generic `sudo make install` method with the `matebook-applet` put in Gnome's autostart as a `.desktop` file. For the `matebook-applet` to be visible, I've installed the Gnome extension `AppIndicator and KStatusNotifierItem Support`.

**Comment by n3vu0r** [comment] 2023-02-22 15:34
I've just noted that I get the message now as well that the device unit is non-existent. I've made a new commit which changes the udev rule and privilege service. It was still working for me, so I'm not sure if it might fix your problem. Can you please pull the latest commit and reinstall with `sudo make install`. Thanks.

**Comment by ahmetlii** [comment] 2023-02-23 20:18
> I have the same Matebook (Model: KPL-W00). I'm running Arch Linux
For reference, I have BOHK-WAX9X and running Arch as well.

> I've just noted that I get the message now as well that the device unit is non-existent. I've made a new commit which changes the udev rule and privilege service. It was still working for me, so I'm not sure if it might fix your problem. Can you please pull the latest commit (`git pull`) and reinstall with `sudo make install`. Thanks.

I've reinstalled, issues partly solved. I have done a clean build by removing all of the huawei-wmi related files in /usr/ and /etc/ then reinstalling kernel (it's >5.5), and there aren't any permission errors anymore nor that particular warning in the systemd service, except that systemctl throws out "The unit files have no installation config" while enabling `huawei-wmi-privilege.service`. However, battery protection still doesn't work, system somehow ignores settings and keeps charging. KDE detects the battery thresholds, though often not noticing changes to the thresholds by matebook-applet (I guess KDE battery notice is refreshed after every boot, rather than checking frequently)

**Comment by n3vu0r** [comment] 2023-02-24 08:01
Thanks.

> The unit files have no installation config

Interesting, the `Makefile` doesn't produce this warning (no failure) when enabling both services with a single command. Enabling them separately will produce it. I made a new commit to only enable the reinstate service while the privilege service is now a so-called static one and "enabled" by the `udev` rule.

Please first disable the old privilege service and then pull and reinstall the latest version:

```sh
sudo systemctl disable huawei-wmi-privilege
sudo make install
```

I guess you should now be free of warnings and errors.

Might still not work for you. In that case, please always check which values the kernel driver sees:

```sh
cat /sys/devices/platform/huawei-wmi/charge_control_thresholds
```

and whether it ignores these values. If it ignores these values (charging above second threshold value), it would be a kernel driver problem.

**Comment by n3vu0r** [comment] 2023-03-05 06:55
> KDE detects the battery thresholds, though often not noticing changes to the thresholds by matebook-applet (I guess KDE battery notice is refreshed after every boot, rather than checking frequently)

I know that Gnome refreshes the charging status periodically with a delay of more than a minute. KDE might do the same. Following gives you the charging status with almost no delay:

```sh
cat /sys/class/power_supply/BAT?/status
```

> For reference, I have BOHK-WAX9X and running Arch as well.

Ok, it seems to be the follow-up model (same produkt name in shops). It should be supported by the kernel driver.

**Closed** 2023-03-07 16:57 UTC

**Comment by ahmetlii** [comment] 2023-03-11 10:37
@n3vu0r thanks for all the help and sorry for a late reply, but I've followed the instructions more than a few times and it seems like it's likely a kernel driver/hardware problem
The thresholds are set, however the driver ignores those after hitting the limit, and charging beyond of it.
likewise ``cat /sys/class/power_supply/BAT?/status`` shows that it's constantly charging during that time.

**Comment by ahmetlii** [comment] 2023-04-19 16:34
Update: Found the main culprit after a month (if anyone is going to read this issue), it turned out that I forgot "Smart Charging" on after updating BIOS and uninstalling Windows. In order to turn it off from Linux, follow the instruction outlined [here](https://github.com/aymanbagabas/Huawei-WMI/issues/55#issuecomment-1028953673).
Also pinging @Rolo1973.

**Comment by n3vu0r** [comment] 2023-04-21 14:34
Ah, I didn't know this. Thanks. I've documented it [here](https://github.com/qu1x/huawei-wmi#smart-charge). But I cannot confirm it myself. Is the summary correct or are one or two `echo`s to the `call` file required as well?
